# Generated by Django 6.0.4 on 2026-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://www.image2url.com/r2/default/images/1777972917474-ed089f2a-e9bc-4515-a35e-c57f62b57c84.jpeg')),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
